"""twitter_user_protected

Revision ID: 6a796fed7f6b
Revises: f763b2d5edfb
Create Date: 2023-03-05 15:39:03.162995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a796fed7f6b'
down_revision = 'f763b2d5edfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('_account', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('_state', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_column('_state')
        batch_op.drop_column('_account')
        batch_op.drop_column('_date')

    # ### end Alembic commands ###
