"""image twitter_user

Revision ID: 87237aadd8ff
Revises: 6a796fed7f6b
Create Date: 2023-03-09 09:27:46.863662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87237aadd8ff'
down_revision = '6a796fed7f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twitter_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twitter_user', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
